// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAGxSAvxTv-4gLV4alzOWvWh8Iqs2X5yQ',
    appId: '1:454466880872:web:d03e3c63d29ca0056382dd',
    messagingSenderId: '454466880872',
    projectId: 'face-recog-kp',
    authDomain: 'face-recog-kp.firebaseapp.com',
    storageBucket: 'face-recog-kp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqnvyqZZVaygCbWwv5RUJ6u_-EWMrhrrY',
    appId: '1:454466880872:android:415b759a5f27cc9d6382dd',
    messagingSenderId: '454466880872',
    projectId: 'face-recog-kp',
    storageBucket: 'face-recog-kp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1x5nR9NBk2nN9dPAWkK6Rr4_RXF1v2Ws',
    appId: '1:454466880872:ios:f7d68c6391fc0f376382dd',
    messagingSenderId: '454466880872',
    projectId: 'face-recog-kp',
    storageBucket: 'face-recog-kp.appspot.com',
    iosClientId: '454466880872-mvfsgf9rupb81biiiu43pau82l7kt782.apps.googleusercontent.com',
    iosBundleId: 'com.example.facialRecog1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1x5nR9NBk2nN9dPAWkK6Rr4_RXF1v2Ws',
    appId: '1:454466880872:ios:f7d68c6391fc0f376382dd',
    messagingSenderId: '454466880872',
    projectId: 'face-recog-kp',
    storageBucket: 'face-recog-kp.appspot.com',
    iosClientId: '454466880872-mvfsgf9rupb81biiiu43pau82l7kt782.apps.googleusercontent.com',
    iosBundleId: 'com.example.facialRecog1',
  );
}
